CREATE TABLE servers (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  ip VARCHAR(32) NOT NULL,
  port INT UNSIGNED DEFAULT(27015) NOT NULL
)